### ISSUE TITLE
sepp can hang forever

### ISSUE THREAD

**Issue by colinbrislawn** [qiime2/q2-fragment-insertion#94]
**Bug Description**

When running on WSL, sepp occasionally finishes, but simply hang forever.

(This has happened to me before, and I'm finally opening an issue!)

```sh
qiime fragment-insertion sepp \
  --i-reference-database dbs/sepp-refs-gg-13-8.qza \
  --i-representative-sequences results_analysis2/dada2_f240_r240/representative_sequences.qza \
  --o-placements               results_analysis2/dada2_f240_r240/tree_placements.qza \
  --o-tree                     results_analysis2/dada2_f240_r240/sepp_tree.qza \
  --p-threads 4 --verbose --p-debug
```

<details><summary>qiime info</summary>

```yaml
System versions
Python version: 3.10.14
QIIME 2 release: 2024.10
QIIME 2 version: 2024.10.1
q2cli version: 2024.10.1

Installed plugins
alignment: 2024.10.0
composition: 2024.10.0
cutadapt: 2024.10.0
dada2: 2024.10.0
deblur: 2024.10.0
demux: 2024.10.0
diversity: 2024.10.0
diversity-lib: 2024.10.0
emperor: 2024.10.0
feature-classifier: 2024.10.0
feature-table: 2024.10.0
fragment-insertion: 2024.10.0
longitudinal: 2024.10.0
metadata: 2024.10.0
phylogeny: 2024.10.0
quality-control: 2024.10.0
quality-filter: 2024.10.0
rescript: 2024.10.0
sample-classifier: 2024.10.0
stats: 0+unknown
taxa: 2024.10.0
types: 2024.10.0
vizard: 0.0.1.dev0
vsearch: 2024.10.0

Application config directory
/home/biouser/miniconda3/envs/qiime2-amplicon-2024.10/var/q2cli

Config
Config Source: /home/biouser/miniconda3/envs/qiime2-amplicon-2024.10/etc/qiime2_config.toml
```

</details> 

EDIT: looks like 'defunct' on Linux means it's finished, but not registered as such by the host process. Interesting!

![Image](https://github.com/user-attachments/assets/dcccdc38-92f0-4baa-81af-c821337a96d6)

![Image](https://github.com/user-attachments/assets/b519cd74-1e30-4d09-99de-07a409460f1e)
